# GitHub Workflow 名称
name: Build Android APK

# 触发工作流程的事件
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 定义工作任务
jobs:
  build-android:
    # 指定运行环境
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # 建议使用LTS版本

      # 3. 设置 Java 环境 (Android 构建需要)
      - name: Set up Java (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # 现代 Android 构建推荐使用 JDK 17

      # 4. 安装项目依赖
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 5. 生成原生 Android 项目
      - name: Generate native Android project
        run: npx expo prebuild --platform android --no-install

      # 6. 构建 Android APK
      # 使用 'assembleRelease' 来构建 APK 文件
      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease
        
      # 7. 上传构建产物 (APK)
      # 将生成的 APK 文件作为产物上传，方便下载
      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-Build-APK
          path: android/app/build/outputs/apk/release/app-release.apk
